name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.4.1-dev.1

homepage: https://vukoye.github.io

environment:
  sdk: ">=3.0.0 <4.0.0"

#dependencies:
#  path: ^1.4.1
dependencies:
  xml: ^6.3.0
  cryptoutils: ^0.5.0
  crypto: ^3.0.3
  synchronized: ^3.1.0
  tuple: ^2.0.1
  unorm_dart: ^0.2.0
  image: ^4.0.17
  quiver: ^3.2.1 #hash code generator
  console: ^4.1.0 #for example
  intl: ^0.18.1
  collection: ^1.17.1
  universal_io: ^2.2.0
  web_socket_channel: ^2.4.0
  jose: ^0.3.2
  uuid: ^4.1.0

dev_dependencies:
  test: ^1.16.8
  mockito: ^5.0.3
  dart_jsonwebtoken: ^2.4.1
